from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field

# Pydantic requires typing_extensions.TypedDict (not typing.TypedDict) on Python < 3.12.
from typing_extensions import TypedDict

from albert.core.base import BaseAlbertModel
from albert.core.shared.models.base import BaseResource


class ChatComponentType(str, Enum):
    """The kind of content a single [`ChatMessage`][albert.resources.chats.ChatMessage] component carries.

    A turn in an "Ask Albert" conversation is stored as one or more message
    components, each of a specific type. The component type determines how the
    ``content`` payload is shaped and how the UI renders it.

    The primary payload is always ``content`` (a string or typed JSON object);
    some user-side structured responses are carried on separate fields, as noted.

    Attributes
    ----------
    TEXT : str
        Prose / markdown assistant or user text (streamed, APPEND semantics).
    IMAGE : str
        Image or code-interpreter chart payload.
    REASONING_BLOCK : str
        Collapsible agent reasoning block.
    NOTEBOOK_CITATION : str
        Citation card linking to a notebook source.
    DOCUMENT_CITATION : str
        Citation card linking to a document source.
    PRODUCT_CARD : str
        Formulation inventory card (feedback-eligible in the UI).
    INGREDIENT_CARD : str
        Ingredient inventory card (feedback-eligible in the UI).
    TOOL_CALL : str
        Structured tool-execution chip (tool name, status, I/O display items);
        REPLACE semantics (latest row per ``component_id`` wins).
    ERROR : str
        An error surfaced to the user.
    PLAN : str
        Supervisor plan artifact (plan content in ``content``); the user's
        approve/answer/changes response is carried on the user message via
        [`plan_action`][albert.resources.chats.ChatMessage.plan_action], not in the plan card's ``content``.
    PERMISSION_REQUEST : str
        Gated SDK-write approval card (permission content in ``content``); the
        user's allow/deny is carried via [`permission_action`][albert.resources.chats.ChatMessage.permission_action]
        on the user message (an ``allow_session`` response persists as a durable
        session grant).
    """

    TEXT = "text"
    IMAGE = "image"
    REASONING_BLOCK = "reasoning_block"
    NOTEBOOK_CITATION = "notebook_citation"
    DOCUMENT_CITATION = "document_citation"
    PRODUCT_CARD = "product_card"
    INGREDIENT_CARD = "ingredient_card"
    TOOL_CALL = "tool_call"
    ERROR = "error"
    PLAN = "plan"
    PERMISSION_REQUEST = "permission_request"


class ChatUserType(str, Enum):
    """Whether a [`ChatMessage`][albert.resources.chats.ChatMessage] was submitted by a person or generated by Albert.

    Attributes
    ----------
    USER : str
        The message was submitted by a person.
    SYSTEM : str
        The message was generated by Albert (the assistant or platform).
    """

    USER = "user"
    SYSTEM = "system"


class ChatRole(str, Enum):
    """The conversation role of a [`ChatMessage`][albert.resources.chats.ChatMessage] in the LLM turn model.

    Attributes
    ----------
    USER : str
        A turn spoken by the user.
    ASSISTANT : str
        A turn spoken by the assistant.
    """

    USER = "user"
    ASSISTANT = "assistant"


class ChatFolderType(str, Enum):
    """The level of a [`ChatFolder`][albert.resources.chats.ChatFolder] within the folder hierarchy.

    Attributes
    ----------
    ROOT : str
        A top-level folder with no parent.
    CHILD : str
        A folder nested inside another folder.
    """

    ROOT = "root"
    CHILD = "child"


class PageContext(TypedDict, total=False):
    """The Albert page a user was viewing when they sent a chat message.

    Captured so "Ask Albert" can ground its answer in the entity the user was
    looking at. All keys are optional.

    Attributes
    ----------
    url : str
        The URL of the page the user was on.
    entity : str
        The type of entity in view (e.g. an inventory item or project).
    albert_id : str
        The Albert ID of the entity in view.
    parent_id : str
        The Albert ID of the entity's parent, when applicable.
    parent_entity : str
        The type of the parent entity, when applicable.
    section : str
        The section or tab of the page in view.
    """

    url: str
    entity: str
    albert_id: str
    parent_id: str
    parent_entity: str
    section: str


class ChatSession(BaseResource):
    """A single "Ask Albert" conversation.

    A chat session is one conversation thread with Albert's AI assistant. It holds
    an ordered series of [`ChatMessage`][albert.resources.chats.ChatMessage] turns and can be filed under a
    [`ChatFolder`][albert.resources.chats.ChatFolder]. A session has a server-assigned ``id`` plus a required
    client-facing ``source_session_id`` that externally links it to the Ask
    session.

    Sessions are managed through
    [`ChatSessionCollection`][albert.collections.chat_sessions.ChatSessionCollection]
    (``client.chat_sessions``).

    Attributes
    ----------
    id : str | None
        The session identifier assigned by Albert. Set once the session is created
        or retrieved.
    name : str
        The display name of the session. Required.
    parent_id : str | None
        The [`ChatFolder`][albert.resources.chats.ChatFolder] this session is filed under, if any. Serialized as
        ``parentId``.
    source_session_id : str
        An external identifier that links this session to a source system.
        Required. Serialized as ``sourceSessionId``.
    last_message_at : str | None
        ISO 8601 timestamp of the most recent message in the session. Read from
        the server. Serialized as ``lastMessageAt``.

    See Also
    --------
    albert.collections.chat_sessions.ChatSessionCollection : Create and manage sessions.
    ChatMessage : The turns that make up a session.
    ChatFolder : Folders that organize sessions.

    !!! example
        ```python
        from albert.resources.chats import ChatSession

        session = ChatSession(name="Titanium dioxide questions", source_session_id="ext-123")
        ```
    """

    id: str | None = Field(default=None)
    name: str
    parent_id: str | None = Field(default=None, alias="parentId")
    source_session_id: str = Field(alias="sourceSessionId")
    last_message_at: str | None = Field(default=None, alias="lastMessageAt")


class ChatMessageAttachment(BaseAlbertModel):
    """A compact reference to a file attached to a chat message.

    Records which files arrived with a message so the transcript can render them.
    Carries display metadata only, never file content or signed URLs.

    Attributes
    ----------
    file_id : str
        The attachment (ATT) ID of the file.
    title : str
        The file's display name.
    kind : str
        The file kind (e.g. ``pdf``, ``image``, ``workbook``, ``csv``).
    size_bytes : int | None
        The file size in bytes.
    parts_summary : str | None
        A human-readable description of the file's structure (e.g. ``"34 pages"``).
    """

    file_id: str = Field(alias="fileId")
    title: str
    kind: str
    size_bytes: int | None = Field(default=None, alias="sizeBytes")
    parts_summary: str | None = Field(default=None, alias="partsSummary")


class ChatMessage(BaseResource):
    """A single turn (or turn component) within an "Ask Albert" conversation.

    A chat message is one component of the back-and-forth inside a
    [`ChatSession`][albert.resources.chats.ChatSession]: a user prompt, an assistant reply, a reasoning block, a
    citation, and so on, as given by its [`ChatComponentType`][albert.resources.chats.ChatComponentType]. Messages are
    addressed by the composite key ``(source_request_id, sequence)`` (``sequence``
    is zero-padded, e.g. ``"000"``); ``id`` exists but lookups use
    ``source_request_id`` + ``sequence``, and [`ChatComponentType`][albert.resources.chats.ChatComponentType] further
    distinguishes components that share a request.

    Messages are managed through
    [`ChatMessageCollection`][albert.collections.chat_messages.ChatMessageCollection]
    (``client.chat_messages``).

    Attributes
    ----------
    id : str | None
        The message identifier assigned by Albert.
    source_request_id : str | None
        Client-generated request trace identifier that groups the components of one
        turn. Auto-generated on create when not set. Serialized as ``sourceRequestId``.
    sequence : str | None
        Zero-padded position of this component within the session (e.g. ``"000"``,
        ``"001"``).
    component_type : ChatComponentType
        The kind of component this message carries (e.g. text, image, reasoning
        block). Required. Serialized as ``componentType``.
    user_type : ChatUserType
        Whether the message originates from a person or from Albert. Required.
        Serialized as ``userType``.
    role : ChatRole
        The LLM conversation role (user or assistant). Required.
    content : str | dict[str, Any]
        The component's payload, shaped by ``component_type``: a string for text or
        a free-form object for richer components. Required. Serialized as ``Content``.
    parent_id : str | None
        The [`ChatSession`][albert.resources.chats.ChatSession] this message belongs to. Present in retrieved
        messages; on create it is taken from the URL path. Serialized as ``parentId``.
    component_id : str | None
        The component instance identifier. Serialized as ``componentId``.
    parent_request_id : str | None
        The source request ID of the parent turn, for branched conversations.
        Serialized as ``parentRequestId``.
    branch_index : int | None
        The branch index, for branched conversations. Serialized as ``branchIndex``.
    span_id : str | None
        A span/trace identifier. Serialized as ``spanId``.
    is_visible : bool | None
        Whether the component is shown in the UI. Serialized as ``isVisible``.
    display_feedback_component : bool | None
        Whether the feedback UI is shown for this message. Serialized as
        ``displayFeedbackComponent``.
    value : list[dict] | None
        api-chat storage/history metadata for the message rows grouped under one
        message ID (revision records, e.g. ``{ts: <epoch>}``). This is NOT the
        component payload; the payload is in ``content``. Do not treat ``value``
        as a general-purpose extra-data field.
    page_context : PageContext | None
        The Albert page the user was viewing when they sent the message. Serialized
        as ``pageContext``.
    attachments : list[ChatMessageAttachment] | None
        Files the user attached to this message, for display in the transcript.
    plan_action : dict[str, Any] | None
        Structured record of a plan approval or change request the user submitted
        with this message (present on user rows that acted on a plan card).
    permission_action : dict[str, Any] | None
        Structured record of a permission decision the user submitted with this
        message (present on user rows that responded to a permission card; an
        allow_session row is the durable session grant).

    See Also
    --------
    albert.collections.chat_messages.ChatMessageCollection : Add and manage messages.
    ChatSession : The conversation a message belongs to.
    ChatComponentType : The set of component types.

    !!! example
        ```python
        from albert.resources.chats import ChatMessage, ChatComponentType, ChatUserType, ChatRole

        message = ChatMessage(
            parent_id="<session id>",
            component_type=ChatComponentType.TEXT,
            user_type=ChatUserType.USER,
            role=ChatRole.USER,
            content="What raw materials contain titanium dioxide?",
        )
        ```
    """

    id: str | None = Field(default=None)
    source_request_id: str | None = Field(default=None, alias="sourceRequestId")
    sequence: str | None = Field(default=None)
    component_type: ChatComponentType = Field(alias="componentType")
    user_type: ChatUserType = Field(alias="userType")
    role: ChatRole = Field(alias="role")
    content: str | dict[str, Any] = Field(alias="Content")
    parent_id: str | None = Field(default=None, alias="parentId")
    component_id: str | None = Field(default=None, alias="componentId")
    parent_request_id: str | None = Field(default=None, alias="parentRequestId")
    branch_index: int | None = Field(default=None, alias="branchIndex")
    span_id: str | None = Field(default=None, alias="spanId")
    is_visible: bool | None = Field(default=None, alias="isVisible")
    display_feedback_component: bool | None = Field(default=None, alias="displayFeedbackComponent")
    value: list[dict] | None = Field(default=None)
    page_context: PageContext | None = Field(default=None, alias="pageContext")
    attachments: list[ChatMessageAttachment] | None = Field(default=None)
    plan_action: dict[str, Any] | None = Field(default=None, alias="planAction")
    permission_action: dict[str, Any] | None = Field(default=None, alias="permissionAction")


class ChatFolder(BaseResource):
    """A folder for organizing "Ask Albert" conversations.

    A chat folder groups related [`ChatSession`][albert.resources.chats.ChatSession] conversations and can be
    nested inside another folder. A session is filed under a folder via the
    session's ``parent_id``.

    Folders are managed through
    [`ChatFolderCollection`][albert.collections.chat_folders.ChatFolderCollection]
    (``client.chat_folders``).

    Attributes
    ----------
    id : str | None
        The folder identifier assigned by Albert. Set once the folder is created
        or retrieved.
    name : str
        The display name of the folder. Required.
    folder_type : ChatFolderType | None
        Whether this is a top-level (root) or nested (child) folder. Serialized as
        ``type``.
    parent_id : str | None
        The parent folder for a nested folder, if any. Serialized as ``parentId``.

    See Also
    --------
    albert.collections.chat_folders.ChatFolderCollection : Create and manage folders.
    ChatSession : The conversations a folder organizes.

    !!! example
        ```python
        from albert.resources.chats import ChatFolder

        folder = ChatFolder(name="Formulation questions")
        ```
    """

    id: str | None = Field(default=None)
    name: str
    folder_type: ChatFolderType | None = Field(default=None, alias="type")
    parent_id: str | None = Field(default=None, alias="parentId")


class ChatFlagType(str, Enum):
    """A marker that can be applied to a [`ChatMessage`][albert.resources.chats.ChatMessage].

    Flags annotate messages in an "Ask Albert" conversation, chiefly to capture
    user feedback and interaction state.

    Attributes
    ----------
    STARRED : str
        The message was starred (marked as notable) by the user.
    DOWNLOADED : str
        The message's content was downloaded.
    REQUESTED : str
        The message was marked as requested.
    HALLUCINATED : str
        The message was flagged as a hallucination (an inaccurate answer).
    """

    STARRED = "starred"
    DOWNLOADED = "downloaded"
    REQUESTED = "requested"
    HALLUCINATED = "hallucinated"


class ChatFlag(BaseResource):
    """A flag applied to a message in an "Ask Albert" conversation.

    A chat flag records a marker (see [`ChatFlagType`][albert.resources.chats.ChatFlagType]) on a specific
    [`ChatMessage`][albert.resources.chats.ChatMessage], identified by its session, request, and sequence. Flags
    are returned by Albert; they are added and removed through
    [`ChatFlagCollection`][albert.collections.chat_flags.ChatFlagCollection]
    (``client.chat_flags``) rather than constructed directly.

    Attributes
    ----------
    source_request_id : str | None
        Request/trace identifier of the flagged message. Serialized as
        ``sourceRequestId``.
    id : str | None
        The flagged message's identifier.
    parent_id : str | None
        The [`ChatSession`][albert.resources.chats.ChatSession] the flagged message belongs to. Serialized as
        ``parentId``.
    type : ChatFlagType | None
        The type of flag.
    component_type : ChatComponentType | None
        The component type of the flagged message. Serialized as ``componentType``.
    sequence : str | None
        Zero-padded sequence of the flagged message within the session.
    starred : bool | None
        Whether the message is starred.
    requested : bool | None
        Whether the message is marked as requested.
    downloaded : bool | None
        Whether the message is marked as downloaded.
    hallucinated : bool | None
        Whether the message is flagged as a hallucination.

    See Also
    --------
    albert.collections.chat_flags.ChatFlagCollection : Add, remove, and list flags.
    ChatFlagType : The set of flag types.
    """

    source_request_id: str | None = Field(default=None, alias="sourceRequestId")
    id: str | None = Field(default=None)
    parent_id: str | None = Field(default=None, alias="parentId")
    type: ChatFlagType | None = Field(default=None)
    component_type: ChatComponentType | None = Field(default=None, alias="componentType")
    sequence: str | None = Field(default=None)
    starred: bool | None = Field(default=None)
    requested: bool | None = Field(default=None)
    downloaded: bool | None = Field(default=None)
    hallucinated: bool | None = Field(default=None)


class ChatFlagsInMessage(BaseAlbertModel):
    """The set of flags currently applied to one chat message.

    Returned by
    [`get_by_message`][albert.collections.chat_flags.ChatFlagCollection.get_by_message] to
    summarize which [`ChatFlagType`][albert.resources.chats.ChatFlagType] markers are set on a single message.

    Attributes
    ----------
    source_request_id : str | None
        Request/trace identifier of the message. Serialized as ``sourceRequestId``.
    total : int | None
        Total number of flags set on the message.
    flags : list[ChatFlagType] | None
        The flag types set on the message.
    """

    source_request_id: str | None = Field(default=None, alias="sourceRequestId")
    total: int | None = None
    flags: list[ChatFlagType] | None = None
