from __future__ import annotations

import re
import uuid
import warnings
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Annotated, Any, Literal

from pandas import DataFrame
from pydantic import Field, model_validator

from albert.core.base import BaseAlbertModel
from albert.core.shared.identifiers import (
    CustomTemplateId,
    LinkId,
    NotebookId,
    ProjectId,
    SynthesisId,
    TaskId,
)
from albert.core.shared.models.base import BaseResource, EntityLink
from albert.exceptions import AlbertException
from albert.resources.acls import ACL, ACLContainer


class ListBlockStyle(str, Enum):
    """The style of a list block.

    Attributes
    ----------
    ORDERED : str
        A numbered list.
    UNORDERED : str
        A bulleted list.
    """

    ORDERED = "ordered"
    UNORDERED = "unordered"


class BlockType(str, Enum):
    """The type of a notebook content block.

    Attributes
    ----------
    PARAGRAPH : str
        A block of free text.
    LIST : str
        A bulleted or numbered list.
    HEADER : str
        A section heading.
    CHECKLIST : str
        A list of checkable items.
    IMAGE : str
        An embedded image.
    ATTACHES : str
        An attached file.
    KETCHER : str
        A chemical structure drawn in the Ketcher editor.
    TABLE : str
        A tabular grid of cells.
    """

    PARAGRAPH = "paragraph"
    LIST = "list"
    HEADER = "header"
    CHECKLIST = "checklist"
    IMAGE = "image"
    ATTACHES = "attaches"
    KETCHER = "ketcher"
    TABLE = "table"


class NotebookCopyType(str, Enum):
    """The kind of copy to perform when copying a notebook.

    Attributes
    ----------
    TEMPLATE : str
        Copy into a notebook template.
    TASK : str
        Copy into a task.
    PROJECT : str
        Copy into a project.
    RESTORE_TEMPLATE : str
        Restore a notebook from a template.
    GEN_TASK_TEMPLATE : str
        Copy into a general task template.
    """

    TEMPLATE = "template"
    TASK = "Task"
    PROJECT = "Project"
    RESTORE_TEMPLATE = "restoreTemplate"
    GEN_TASK_TEMPLATE = "genTaskTemplate"


class BaseBlock(BaseAlbertModel):
    """Common fields shared by every notebook block.

    Attributes
    ----------
    id : str
        The block's unique identifier. Generated automatically (a UUID) if not
        provided.
    version : datetime | None
        The version timestamp of the block, set by Albert.
    """

    # id's are autogenerated by EditorJS without any particular pattern. The SDK will use uuid4.
    id: str = Field(default_factory=lambda: str(uuid.uuid4()), alias="albertId")
    version: datetime | None = Field(default=None)


class HeaderContent(BaseAlbertModel):
    """The content of a header block.

    Attributes
    ----------
    level : int
        The heading level (1 is the largest heading).
    text : str | None
        The heading text.
    """

    level: int = Field(ge=1)
    text: str | None


class HeaderBlock(BaseBlock):
    """A section heading in a notebook.

    Attributes
    ----------
    type : BlockType
        Always [`HEADER`][albert.resources.notebooks.BlockType.HEADER].
    content : HeaderContent
        The heading level and text.

    Examples
    --------
    ```python
    from albert.resources.notebooks import HeaderBlock, HeaderContent

    block = HeaderBlock(content=HeaderContent(level=1, text="Procedure"))
    ```
    """

    type: Literal[BlockType.HEADER] = Field(default=BlockType.HEADER, alias="blockType")
    content: HeaderContent


class ParagraphContent(BaseAlbertModel):
    """The content of a paragraph block.

    Attributes
    ----------
    text : str | None
        The paragraph text.
    """

    text: str | None


class ParagraphBlock(BaseBlock):
    """A block of free text in a notebook.

    Attributes
    ----------
    type : BlockType
        Always [`PARAGRAPH`][albert.resources.notebooks.BlockType.PARAGRAPH].
    content : ParagraphContent
        The paragraph text.

    Examples
    --------
    ```python
    from albert.resources.notebooks import ParagraphBlock, ParagraphContent

    block = ParagraphBlock(content=ParagraphContent(text="Weighed 1.2 g."))
    ```
    """

    type: Literal[BlockType.PARAGRAPH] = Field(default=BlockType.PARAGRAPH, alias="blockType")
    content: ParagraphContent


class ChecklistItem(BaseAlbertModel):
    """A single entry in a checklist block.

    Attributes
    ----------
    checked : bool
        Whether the item is checked.
    text : str
        The item's label text.
    """

    checked: bool
    text: str


class ChecklistContent(BaseAlbertModel):
    """The content of a checklist block.

    Attributes
    ----------
    items : list[ChecklistItem]
        The checklist entries, in order.
    """

    items: list[ChecklistItem]


class ChecklistBlock(BaseBlock):
    """A list of checkable items in a notebook.

    Attributes
    ----------
    type : BlockType
        Always [`CHECKLIST`][albert.resources.notebooks.BlockType.CHECKLIST].
    content : ChecklistContent
        The checklist items.

    Examples
    --------
    ```python
    from albert.resources.notebooks import (
        ChecklistBlock,
        ChecklistContent,
        ChecklistItem,
    )

    block = ChecklistBlock(
        content=ChecklistContent(
            items=[ChecklistItem(text="Calibrate scale", checked=False)]
        )
    )
    ```
    """

    type: Literal[BlockType.CHECKLIST] = Field(default=BlockType.CHECKLIST, alias="blockType")
    content: ChecklistContent

    def is_checked(self, *, target_text: str) -> bool | None:
        """Return the checked state of a checklist item by its text.

        Parameters
        ----------
        target_text : str
            The label text of the checklist entry to look up.

        Returns
        -------
        bool | None
            The checked state of the matching entry, or ``None`` if no entry has
            the given text.
        """
        # loop items
        for i in self.content.items:
            if i.text == target_text:
                # return check state
                return i.checked

        # return None if no match
        return


class AttachesContent(BaseAlbertModel):
    """The content of a file attachment block.

    Provide either ``file_path`` (a local file to upload) or ``file_key`` (an
    already-uploaded file) when building the block.

    Attributes
    ----------
    title : str | None
        The display title of the attachment. Defaults to the file name.
    namespace : str
        The file storage namespace. Defaults to ``"result"``.
    file_key : str | None
        The storage key of the uploaded file on Albert.
    format : str | None
        The MIME type of the file (e.g. ``"application/pdf"``). Inferred from the
        file name if not set.
    file_path : str | Path | None
        Path to a local file to upload. Not stored on the server.
    signed_url : str | None
        A temporary download URL for the file, populated by Albert. Read-only.
    """

    title: str | None = Field(default=None)
    namespace: str = Field(default="result")
    file_key: str | None = Field(default=None, alias="fileKey")
    format: str | None = Field(default=None, alias="mimeType")
    file_path: str | Path | None = Field(default=None, exclude=True)
    signed_url: str | None = Field(default=None, alias="signedURL", exclude=True, frozen=True)


class AttachesBlock(BaseBlock):
    """An attached file in a notebook.

    Attributes
    ----------
    type : BlockType
        Always [`ATTACHES`][albert.resources.notebooks.BlockType.ATTACHES].
    content : AttachesContent
        The attachment details.

    Examples
    --------
    ```python
    from albert.resources.notebooks import AttachesBlock, AttachesContent

    block = AttachesBlock(
        content=AttachesContent(file_path="/path/to/spectrum.pdf")
    )
    ```
    """

    type: Literal[BlockType.ATTACHES] = Field(default=BlockType.ATTACHES, alias="blockType")
    content: AttachesContent


class ImageContent(BaseAlbertModel):
    """The content of an image block.

    Provide either ``file_path`` (a local image to upload) or ``file_key`` (an
    already-uploaded image) when building the block.

    Attributes
    ----------
    title : str | None
        The caption or title of the image.
    namespace : str
        The file storage namespace. Defaults to ``"result"``.
    stretched : bool
        Whether the image is stretched to full width.
    with_background : bool
        Whether the image is shown with a background.
    with_border : bool
        Whether the image is shown with a border.
    file_key : str | None
        The storage key of the uploaded image on Albert.
    format : str | None
        The MIME type of the image (e.g. ``"image/png"``). Inferred from the file
        name if not set.
    file_path : str | Path | None
        Path to a local image to upload. Not stored on the server.
    signed_url : str | None
        A temporary download URL for the image, populated by Albert. Read-only.
    """

    title: str | None = Field(default=None)
    namespace: str = Field(default="result")
    stretched: bool = Field(default=False)
    with_background: bool = Field(default=False, alias="withBackground")
    with_border: bool = Field(default=False, alias="withBorder")
    file_key: str | None = Field(default=None, alias="fileKey")
    format: str | None = Field(default=None, alias="mimeType")
    file_path: str | Path | None = Field(default=None, exclude=True)
    signed_url: str | None = Field(default=None, alias="signedURL", exclude=True, frozen=True)


class ImageBlock(BaseBlock):
    """An embedded image in a notebook.

    Attributes
    ----------
    type : BlockType
        Always [`IMAGE`][albert.resources.notebooks.BlockType.IMAGE].
    content : ImageContent
        The image details.

    Examples
    --------
    ```python
    from albert.resources.notebooks import ImageBlock, ImageContent

    block = ImageBlock(content=ImageContent(file_path="/path/to/plot.png"))
    ```
    """

    type: Literal[BlockType.IMAGE] = Field(default=BlockType.IMAGE, alias="blockType")
    content: ImageContent


class KetcherContent(BaseAlbertModel):
    """The content of a Ketcher chemical-structure block.

    When creating a new Ketcher block, set ``smiles`` to the structure's SMILES
    string; the remaining fields are populated by Albert. Existing Ketcher blocks
    cannot be edited in place.

    Attributes
    ----------
    synthesis_id : SynthesisId | None
        The ID of the synthesis backing the drawing (format ``SYN...``). Set by
        Albert when the block is created.
    id : str | None
        The internal content ID.
    block_id : str | None
        The ID of the block this content belongs to.
    data : str | None
        The raw Ketcher canvas data.
    file_key : str | None
        The storage key of the rendered structure.
    s3_key : str | None
        The storage key of the associated synthesis canvas.
    png : str | None
        A PNG rendering of the structure.
    state_type : str
        The state context of the drawing. Defaults to ``"project"``.
    smiles : str | None
        The SMILES string describing the chemical structure.
    """

    synthesis_id: SynthesisId | None = Field(default=None, alias="synthesisId")
    id: str | None = Field(default=None)
    block_id: str | None = Field(default=None, alias="blockId")
    data: str | None = Field(default=None, exclude=True)
    file_key: str | None = Field(default=None, alias="fileKey")
    s3_key: str | None = Field(default=None, alias="s3Key")
    png: str | None = Field(default=None, exclude=True)
    state_type: str = Field(default="project", alias="stateType")
    smiles: str | None = Field(default=None, alias="smiles", exclude=True)


class KetcherBlock(BaseBlock):
    """A chemical structure drawn in the Ketcher editor.

    Attributes
    ----------
    type : BlockType
        Always [`KETCHER`][albert.resources.notebooks.BlockType.KETCHER].
    content : KetcherContent
        The structure details, typically built from a SMILES string.

    Examples
    --------
    ```python
    from albert.resources.notebooks import KetcherBlock, KetcherContent

    block = KetcherBlock(content=KetcherContent(smiles="CCO"))
    ```
    """

    type: Literal[BlockType.KETCHER] = Field(default=BlockType.KETCHER, alias="blockType")
    content: KetcherContent


class TableContent(BaseAlbertModel):
    """The content of a table block.

    Attributes
    ----------
    content : list[list[str | None]]
        The table cells as a list of rows, each row a list of cell values.
    with_headings : bool
        Whether the first row should be treated as column headings.
    """

    content: list[list[str | None]]
    with_headings: bool = Field(default=False, alias="withHeadings")


class TableBlock(BaseBlock):
    """A tabular grid of cells in a notebook.

    Attributes
    ----------
    type : BlockType
        Always [`TABLE`][albert.resources.notebooks.BlockType.TABLE].
    content : TableContent
        The table cells.

    Examples
    --------
    ```python
    from albert.resources.notebooks import TableBlock, TableContent

    block = TableBlock(
        content=TableContent(
            content=[["Trial", "Yield"], ["1", "82%"]],
            with_headings=True,
        )
    )
    ```
    """

    type: Literal[BlockType.TABLE] = Field(default=BlockType.TABLE, alias="blockType")
    content: TableContent

    def to_df(self, *, infer_header: bool = True) -> DataFrame:
        """Convert the table block's content to a pandas DataFrame.

        Parameters
        ----------
        infer_header : bool, default True
            If ``True``, use the first row as column names (with HTML formatting
            stripped) and drop it from the data.

        Returns
        -------
        DataFrame
            The block's content as a pandas DataFrame.
        """

        # convert to df
        df = DataFrame(self.content.content)

        if infer_header:
            # clean df -> column name w/o formatting
            df.columns = df.iloc[0, :]
            df.columns = [re.sub(r"<.*?>", "", x) for x in df.columns]
            # discard first
            df = df.iloc[1:, :].reset_index(drop=True)

        # return df
        return df


class NotebookListItem(BaseAlbertModel):
    """A single entry in a list block, which may itself contain nested entries.

    Attributes
    ----------
    content : str | None
        The item's text.
    items : list[NotebookListItem]
        Nested sub-items beneath this entry.
    """

    content: str | None
    items: list[NotebookListItem] = Field(default_factory=list)


class BulletedListContent(BaseAlbertModel):
    """The content of a bulleted (unordered) list block.

    Attributes
    ----------
    items : list[NotebookListItem]
        The list entries, in order.
    style : ListBlockStyle
        Always [`UNORDERED`][albert.resources.notebooks.ListBlockStyle.UNORDERED].
    """

    items: list[NotebookListItem]
    style: Literal[ListBlockStyle.UNORDERED] = Field(default=ListBlockStyle.UNORDERED)


class NumberedListContent(BaseAlbertModel):
    """The content of a numbered (ordered) list block.

    Attributes
    ----------
    items : list[NotebookListItem]
        The list entries, in order.
    style : ListBlockStyle
        Always [`ORDERED`][albert.resources.notebooks.ListBlockStyle.ORDERED].
    """

    items: list[NotebookListItem]
    style: Literal[ListBlockStyle.ORDERED] = Field(default=ListBlockStyle.ORDERED)


ListContent = Annotated[NumberedListContent | BulletedListContent, Field(discriminator="style")]


class ListBlock(BaseBlock):
    """A bulleted or numbered list in a notebook.

    Attributes
    ----------
    type : BlockType
        Always [`LIST`][albert.resources.notebooks.BlockType.LIST].
    content : NumberedListContent | BulletedListContent
        The list entries and style.

    Examples
    --------
    ```python
    from albert.resources.notebooks import (
        ListBlock,
        BulletedListContent,
        NotebookListItem,
    )

    block = ListBlock(
        content=BulletedListContent(
            items=[NotebookListItem(content="First step")]
        )
    )
    ```
    """

    type: Literal[BlockType.LIST] = Field(default=BlockType.LIST, alias="blockType")
    content: ListContent


class NotebookLink(BaseAlbertModel):
    """A link from a notebook to another Albert entity.

    Attributes
    ----------
    id : LinkId | None
        The ID of the link (format ``LNK...``).
    child : EntityLink
        The linked entity.
    """

    id: LinkId | None = Field(default=None)
    child: EntityLink = Field(..., alias="Child")


_NotebookBlockUnion = (
    HeaderBlock
    | ParagraphBlock
    | ChecklistBlock
    | AttachesBlock
    | ImageBlock
    | KetcherBlock
    | TableBlock
    | ListBlock
)
NotebookBlock = Annotated[_NotebookBlockUnion, Field(discriminator="type")]


class Notebook(BaseResource):
    """An electronic lab notebook (ELN) in Albert.

    A Notebook is an ordered document of content blocks (paragraphs, headers,
    checklists, tables, images, attachments, lists, and Ketcher chemical drawings)
    attached to a parent Project, Task, or custom template. Notebooks are created
    empty and then populated block-by-block; see
    [`NotebookCollection`][albert.collections.notebooks.NotebookCollection] for the workflow.

    Attributes
    ----------
    id : NotebookId | None
        The Albert ID of the notebook (format ``NTB...``). Set once the notebook
        exists on Albert.
    name : str
        The notebook's name. Defaults to ``"Untitled Notebook"``.
    parent_id : ProjectId | TaskId | CustomTemplateId
        The entity the notebook is attached to (a Project ``PRO...``, Task
        ``TAS...``, or custom template ``CTP...``).
    version : datetime | None
        The version timestamp of the notebook, set by Albert.
    blocks : list[NotebookBlock]
        The ordered content blocks of the notebook.
    links : list[NotebookLink] | None
        Links from this notebook to other Albert entities.

    Examples
    --------
    ```python
    from albert.resources.notebooks import Notebook

    notebook = Notebook(name="Trial 1 log", parent_id="PRO123")
    ```
    """

    id: NotebookId | None = Field(default=None, alias="albertId")
    name: str = Field(default="Untitled Notebook")
    parent_id: ProjectId | TaskId | CustomTemplateId = Field(..., alias="parentId")
    version: datetime | None = Field(default=None)
    blocks: list[NotebookBlock] = Field(default_factory=list)
    links: list[NotebookLink] | None = Field(default=None)


NotebookContent = (
    HeaderContent
    | ParagraphContent
    | ChecklistContent
    | AttachesContent
    | ImageContent
    | KetcherContent
    | TableContent
    | BulletedListContent
    | NumberedListContent
)

allowed_notebook_contents = {
    BlockType.HEADER: HeaderContent,
    BlockType.PARAGRAPH: ParagraphContent,
    BlockType.CHECKLIST: ChecklistContent,
    BlockType.ATTACHES: AttachesContent,
    BlockType.IMAGE: ImageContent,
    BlockType.KETCHER: KetcherContent,
    BlockType.TABLE: TableContent,
    BlockType.LIST: (BulletedListContent, NumberedListContent),
}


class PutOperation(str, Enum):
    """The operation to apply to a block when saving notebook content.

    Attributes
    ----------
    UPDATE : str
        Create or update the block.
    DELETE : str
        Remove the block from the notebook.
    """

    UPDATE = "update"
    DELETE = "delete"


class PutBlockDatum(BaseAlbertModel):
    id: str
    operation: PutOperation
    type: BlockType | None = Field(default=None, alias="blockType")
    content: NotebookContent | None = Field(default=None)
    previous_block_id: str | None = Field(default=None, alias="previousBlockId")

    @model_validator(mode="after")
    def content_matches_type(self) -> PutBlockDatum:
        if self.content is None:
            return self  # skip check if there's no content

        content_type = allowed_notebook_contents.get(self.type)
        if content_type and not isinstance(self.content, content_type):
            msg = f"The content type and block type do not match. [content_type={type(self.content)}, block_type={self.type}]"
            raise AlbertException(msg)
        return self

    def model_dump(self, **kwargs) -> dict[str, Any]:
        """
        Shallow model_dump to exclude None values (None only removed from top level).
        This ensures required attrs are not removed.
        """
        base = super().model_dump(**kwargs)
        return {k: v for k, v in base.items() if v is not None}


class PutBlockPayload(BaseAlbertModel):
    data: list[PutBlockDatum]

    def model_dump(self, **kwargs) -> dict[str, Any]:
        """model_dump to ensure only top-level None attrs are removed on PutBlockDatum."""
        return {"data": [item.model_dump(**kwargs) for item in self.data]}


class NotebookCopyACL(BaseResource):
    """
    Access settings applied to a copied notebook.

    Warning
    -----
    Deprecated and will be removed in 2.0. Use ``ACLContainer`` instead.

    Attributes
    ----------
    fgclist : list[ACL]
        Specific access rules for users or teams.
    acl_class : str
        Default access class (for example, "restricted" or "confidential").
    """

    fgclist: list[ACL] = Field(default=None)
    acl_class: str = Field(alias="class")

    def __init__(self, **data):
        warnings.warn(
            "NotebookCopyACL is deprecated and will be removed in 2.0; use ACLContainer instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        super().__init__(**data)


class NotebookCopyInfo(BaseAlbertModel):
    """Instructions for copying a notebook into a new parent.

    Attributes
    ----------
    id : NotebookId
        The ID of the source notebook to copy (format ``NTB...``).
    parent_id : str
        The ID of the destination parent to copy the notebook into.
    notebook_name : str | None
        The name to give the copied notebook.
    name : str | None
        An optional alternative name for the copy.
    acl : ACLContainer | NotebookCopyACL | None
        Access-control settings to apply to the copy.

    Examples
    --------
    ```python
    from albert.resources.notebooks import NotebookCopyInfo

    info = NotebookCopyInfo(id="NTB123", parent_id="PRO456")
    ```
    """

    id: NotebookId
    parent_id: str = Field(alias="parentId")
    notebook_name: str | None = Field(default=None, alias="notebookName")
    name: str | None = Field(default=None)
    acl: ACLContainer | NotebookCopyACL | None = Field(default=None)
