site_name: "Albert Python SDK Docs"
theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            extensions:
              - griffe_pydantic:
                  schema: true
            annotations_path: brief
            show_submodules: true
            members_order: source
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            signature_crossrefs: true
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
          rendering:
            show_source: false
            show_root_heading: true
            heading_level: 2
            show_bases: false  # Hides inherited classes at the top
            group_by_category: true  # Prevents automatic category grouping
            show_docstring_attributes: true
            show_if_no_docstring: true
            separate_signature: true
            show_field_details: true
            allow_inspection: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - SDK Reference:
    - Attachments: attachments.md
    - Cas: cas.md