version: "2.1"

orbs:
  python: circleci/python@2.1.1

jobs:
  tests:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Check Formatting
          command: |
            poetry run ruff format . --check
      - run:
          name: Check Linting
          command: |
            poetry run ruff check .
      - run:
          name: Run pytest
          command: |
            poetry run pytest

workflows:
  main:
    jobs:
      - tests:
          name: Tests

